export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  fortyGuardApiKey: process.env.FORTYGUARD_API_KEY ?? "",
  fortyGuardBaseUrl: process.env.FORTYGUARD_BASE_URL ?? "https://api.fortyguard.com",
  fortyGuardEnabled: process.env.FORTYGUARD_ENABLED !== "false",
  mockMode: process.env.HEATCHECK_MOCK_MODE === "true",
  allowMockFallback: process.env.HEATCHECK_ALLOW_MOCK_FALLBACK === "true",
  cacheTtlSeconds: Number(process.env.HEATCHECK_CACHE_TTL_SECONDS ?? 600),
  groqApiKey: process.env.GROQ_API_KEY ?? "",
  groqModel: process.env.GROQ_MODEL ?? "qwen/qwen3.6-27b",
  agentEnabled: process.env.HEATCHECK_AGENT_ENABLED !== "false",
};
