import { Activity, ArrowDownRight, BrainCircuit, Check, Compass, Crosshair, MapPinned, ShieldCheck, ThermometerSun, Wind } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { PublicAction, PublicShell, publicAssets } from "@/components/PublicShell";
import { useState } from "react";

const intelligence = [
  { id: "01", stage: "Detect", title: "Live thermal intelligence", text: "Spatial heat signals reveal where conditions are changing across the worksite.", readout: "Surface anomaly / 42.7°C", outcome: "Locate the heat zone before it becomes a field condition.", icon: ThermometerSun, image: publicAssets.urbanScan },
  { id: "02", stage: "Detect", title: "Environmental context", text: "Temperature, humidity, wet-bulb, air-quality and solar inputs form one operational reading.", readout: "Wet-bulb / 29.1°C", outcome: "Separate temperature from the exposure conditions that compound it.", icon: Wind, image: publicAssets.layers },
  { id: "03", stage: "Interpret", title: "Decision engine", text: "A constrained decision service weighs exposure, severity, and approved response policy.", readout: "Risk synthesis / 89", outcome: "Turn multiple signals into one explainable operational priority.", icon: BrainCircuit },
  { id: "04", stage: "Respond", title: "Autonomous response", text: "A durable action record captures escalation, approvals, protocol activation, and what happens next.", readout: "Protocol state / armed", outcome: "Create a governed action path with a durable decision record.", icon: Activity },
  { id: "05", stage: "Respond", title: "Urban heat intelligence", text: "Built form, shade, hardscape, and vegetation provide context for repeat risk patterns.", readout: "Pattern context / active", outcome: "Use repeat spatial context to improve the next decision.", icon: Crosshair, image: publicAssets.operations },
];

function DetailHero({ index, eyebrow, title, copy, image }: { index: string; eyebrow: string; title: string; copy: string; image?: string }) {
  return <section className="detail-hero field-signal"><div className="detail-hero__grid" /><div className="detail-hero__copy"><p className="public-kicker">{index} / {eyebrow}</p><h1>{title}</h1><p>{copy}</p><PublicAction>Open workspace</PublicAction></div>{image && <div className="detail-hero__image"><img src={image} alt="" /><div /></div>}</section>;
}

export function PlatformPage() {
  const stages = [["01", "Observe", "Bounded environmental monitoring runs identify locations that are due and collect a compact observation."], ["02", "Analyze", "Heatcheck calculates a deterministic score from thermal, environmental, and exposure signals."], ["03", "Decide", "Structured response logic proposes only permitted actions and records its reasoning."], ["04", "Verify", "Confirmed internal protocol activation can trigger a labelled re-evaluation and a durable audit trail."]];
  return <PublicShell><DetailHero index="01" eyebrow="Platform" title="A measured path from condition to action." copy="Heatcheck turns environmental signals into decisions that operational teams can inspect, govern, and act on." image={publicAssets.terrain} /><section className="detail-section"><div className="detail-heading"><p className="public-kicker">THE OPERATING LOOP</p><h2>One operating model. Every location.</h2></div><div className="stage-list">{stages.map(([id, title, copy]) => <article key={id}><span>{id}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="detail-split detail-split--dark"><div><p className="public-kicker">OPERATIONS SURFACE</p><h2>Quiet interface. Active system.</h2><p>The protected workspace brings live observations, hotspots, incidents, decisions, approvals, and analytics into a tenant-scoped command surface.</p></div><img src={publicAssets.operations} alt="Abstract thermal operations landscape" /></section></PublicShell>;
}

export function IntelligencePage() {
  const [activeIndex, setActiveIndex] = useState(0);
  const active = intelligence[activeIndex];
  const ActiveIcon = active.icon;

  return <PublicShell><DetailHero index="02" eyebrow="Intelligence" title="Five layers. One operational picture." copy="Heatcheck gathers each signal in sequence, then makes the operational chain visible—from detection to governed response." image={publicAssets.layers} /><section className="detail-section intelligence-system"><div className="detail-heading"><p className="public-kicker">INTELLIGENCE SYSTEM / 01—05</p><h2>Read the field in a deliberate order.</h2><p>Choose a layer to inspect its field reading, operational purpose, and contribution to the response chain.</p></div><div className="intelligence-sequence"><nav className="intelligence-navigator" aria-label="Heatcheck intelligence layers">{intelligence.map((layer, index) => <button key={layer.id} type="button" onClick={() => setActiveIndex(index)} className={index === activeIndex ? "is-active" : ""} aria-pressed={index === activeIndex}><span>{layer.id}</span><div><small>{layer.stage}</small><strong>{layer.title}</strong></div><ArrowDownRight size={17} /></button>)}</nav><article className="intelligence-spotlight" key={active.id}><div className="intelligence-spotlight__visual">{active.image ? <img src={active.image} alt="" /> : <div className="intelligence-spotlight__signal"><ActiveIcon size={46} /><i /><i /><i /></div>}<div className="intelligence-spotlight__scan" /><span className="intelligence-spotlight__index">{active.id}</span></div><div className="intelligence-spotlight__content"><div className="intelligence-spotlight__meta"><span>{active.stage} layer</span><span>Live sequence</span></div><ActiveIcon size={23} /><h3>{active.title}</h3><p>{active.text}</p><div className="intelligence-readout"><span>Field reading</span><strong>{active.readout}</strong></div><p className="intelligence-outcome">{active.outcome}</p></div></article></div><div className="intelligence-stage-grid">{["Detect", "Interpret", "Respond"].map((stage) => <div key={stage}><span>{stage}</span><p>{intelligence.filter((layer) => layer.stage === stage).map((layer) => layer.id).join(" / ")}</p></div>)}</div></section><section className="detail-split intelligence-bridge"><div><p className="public-kicker">RESPONSE CONTEXT</p><h2>Evidence first. Action second.</h2><p>Environmental layers flow into a deterministic risk score before any response policy can create an action record.</p><PublicAction href="/platform" subtle>Explore the platform</PublicAction></div><div className="detail-figure"><BrainCircuit size={42} /><span>Environmental signal</span><ArrowDownRight /><strong>Governed response</strong></div></section></PublicShell>;
}

export function SolutionsPage() {
  const solutions = [["Logistics", "Protect loading, yard, and last-mile operations when heat conditions become unstable."], ["Construction", "Give field leaders a live exposure context before outdoor work becomes unsafe."], ["Warehousing", "Monitor docks, roof zones, and material-handling flows across thermal variations."], ["Campuses & cities", "Use spatial heat signals to understand public and workforce exposure at scale."], ["Energy & manufacturing", "Connect site conditions with procedural response and a durable audit trail."]];
  return <PublicShell><DetailHero index="03" eyebrow="Solutions" title="Built where heat becomes operational risk." copy="Heatcheck adapts a shared heat-intelligence system to the locations, workers, and response policies of each operational environment." image={publicAssets.operations} /><section className="detail-section solutions-section"><div className="detail-heading"><p className="public-kicker">FIELD CONTEXTS</p><h2>Same intelligence. Different operation.</h2></div><div className="solutions-list">{solutions.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div><MapPinned /></article>)}</div></section><section className="detail-split detail-split--signal"><div><p className="public-kicker">START SMALL</p><h2>Begin with one location.</h2><p>Calibrate a field site, run a simulation, inspect the decision ledger, then extend the response model across the network.</p><PublicAction>Start Heatcheck</PublicAction></div><div className="signal-list">{["Connect a location", "Confirm governance", "Run a field analysis", "Review the response"].map((item, index) => <span key={item}><i>{index + 1}</i>{item}</span>)}</div></section></PublicShell>;
}

export function CompanyPage() {
  const plans = [["Monitor", "Baseline environmental signal for a focused operation."], ["Autonomous", "Response workflows and agent history for active sites."], ["Enterprise", "Network governance and custom operational integration."]];
  const faqs = [["How does Heatcheck start?", "Create a secure workspace, calibrate a location, and use Simulation Mode before live provider credentials are configured."], ["Can we require approval?", "Yes. Heatcheck records action permissions and presents approval-required actions in the protected queue."], ["What happens in Autonomous mode?", "The system can activate its internal Heatcheck protocol state for eligible severe-risk conditions and persist a labelled re-evaluation."]];
  return <PublicShell><DetailHero index="04" eyebrow="Company" title="Deploy with intent. Govern with evidence." copy="Heatcheck is designed for operations that need clear boundaries between environmental observation, decision support, autonomous protocol activation, and human approval." /><section className="detail-section"><div className="detail-heading"><p className="public-kicker">DEPLOYMENT LEVELS</p><h2>Calibrate the response to the operation.</h2></div><div className="plan-grid">{plans.map(([title, copy], index) => <article key={title} className={index === 1 ? "plan-grid__featured" : ""}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p><PublicAction href="/app" subtle>Discuss deployment</PublicAction></article>)}</div></section><section className="detail-section company-faq"><div className="detail-heading"><p className="public-kicker">GOVERNANCE NOTES</p><h2>Useful answers before the first incident.</h2></div><Accordion type="single" collapsible>{faqs.map(([question, answer], index) => <AccordionItem value={`company-${index}`} key={question}><AccordionTrigger>{question}</AccordionTrigger><AccordionContent>{answer}</AccordionContent></AccordionItem>)}</Accordion></section><section className="company-cta"><ShieldCheck size={24} /><p className="public-kicker">FIELD BRIEFING</p><h2>Make heat response part of the operating system.</h2><PublicAction href="mailto:hello@heatcheck.ai?subject=Heatcheck%20field%20briefing">Talk to Heatcheck</PublicAction></section></PublicShell>;
}
